name: CVE Scanning for Node.js

on:
  schedule:
    - cron: '0 8,18 * * 1-5'
  pull_request:
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'allow-list.json'
      - '.github/workflows/cve-scanning-node.yml'

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --prod
      - run: npx --yes auditjs ossi --whitelist allow-list.json
