name: Lint Code Base

on: [pull_request]

env: # environment variables (available in any part of the action)
  NODE_VERSION: 16

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps: # list of steps
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm i
  
      - name: Code Linting
        run: npm run lint