name: Code Cleanliness

on: [pull_request]

env: # environment variables (available in any part of the action)
  NODE_VERSION: 18

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps: # list of steps
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install --workspaces
  
      - name: Code Linting
        run: |
          npm run lint
          npm run lint --workspaces --if-present