name: Code Cleanliness

on: [pull_request]

env: # environment variables (available in any part of the action)
  NODE_VERSION: 18

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps: # list of steps
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm i
  
      - name: Code Linting
        run: |
          npm run lint
          npm run lint --workspaces